# MultiQC config para ONT Assembly Pipeline v1.30
title: "EPIMOL - ONT Assembly Pipeline Report"
subtitle: "Quality control, assembly metrics and coverage analysis"
intro_text: "This report contains QC metrics for Oxford Nanopore sequencing data, assembly statistics, taxonomy, and coverage analysis."

# Opciones del reporte
show_analysis_paths: False
show_analysis_time: True
default_view: 'report'

custom_logo: "conf/multiqc/logo.png"
custom_logo_url: "https://fisabio.san.gva.es/es/"
custom_logo_title: "FISABIO"

sp:
  busco_summary:
    # El ID 'busco_summary' debe coincidir con el ID de 'custom_data'
    fn: "**/busco/busco_summary.tsv"

# Ignorar archivos problemáticos de nanostats
fn_ignore_files:
  - '**/nanostats/*_n50.json'
  - '**/nanostats/*_mean*.json'
  - '*flagstat*'
  - '*.bam'

# Excluir módulos no deseados
module_order_exclude:
  - samtools_flagstat
  - samtools_idxstats

# Orden de módulos
module_order:
  - nanostat
  - checkm2
  - samtools
  - kraken
  - quast
  - mosdepth
  - prokka
  - custom_content

# Orden de secciones del reporte
report_section_order:
  nanostat:
    order: 2000
  checkm2:
    order: 900
  samtools:
    order: 800
  kraken:
    order: 700
  quast:
    order: 600
  mosdepth:
    order: 500
  prokka:
    order: 400
  custom_content:
    order: 300

# Información de versiones de software
software_versions:
  quality_control_and_filtering:
    porechop: "0.2.4"
    filtlong: "0.3.0"
    nanoplot: "1.46.1"
  de_novo_assembly:
    canu: "2.3"
    flye: "2.9.6"
    hifiasm: "0.25.0"
  polishing_and_assembly_evaluation:
    medaka: "2.1.1"
    quast: "5.3.0"
    checkm2: "1.1.0"
  mapping_and_alignment:
    minimap2: "2.30"
    bwa: "0.7.19"
  post-mapping_analysis:
    Samtools: "1.22.1"
    mosdepth: "0.3.10"
    bcftools: "1.22"
    bedtools: "2.31.1"
  functional_and_taxonomic_analysis:
    prokka: "1.14.6"
    kraken2: "2.1.6"
    blast: "2.16.0"
    diamond: "2.1.13"
  utilities_and_reporting:
    entrez-direct: "22.4"
    multiqc: "1.31"

# Información del header del reporte
report_header_info:
  - Contact E-mail: "vigilancia.genomica@fisabio.es"
  - Sequencing Platform: "Oxford Nanopore Mk1C"
  - Sequencer ID: "MC112687"
  - Dorado_version: "1.1.1"
  - Dorado_model: "dna_r10.4.1_e8.2_400bps_sup@v5.2.0"

# ============================================
# CONFIGURACIÓN CRÍTICA DE COLUMNAS - CORREGIDA
# ============================================

# 1. Control de visibilidad de columnas (qué columnas mostrar/ocultar)
table_columns_visible:
  # NanoStat - Usar los nombres exactos del módulo
  NanoStat:
    "Number of reads_fastq": true
    "Total bases_fastq": true
    "Mean read length_fastq": true
    "Median read length_fastq": false
    "Read length N50_fastq": true
    "Mean read quality_fastq": true
    # Ocultar las que no necesitas
    "Active channels": false
    
  # CheckM2
  CheckM2:
    Completeness: true
    Contamination: true
    "Completeness_Model_Used": false
    "Translation_Table_Used": false
    
  # Samtools Stats - Nombre exacto con espacio
  "Samtools Stats":
    raw_total_sequences: true
    reads_mapped: true
    reads_mapped_percent: true
    average_length: true
    error_rate: false
    
  # Samtools Flagstat (si decides incluirlo)
  "Samtools Flagstat":
    mapped_passed: true
    mapped_passed_pct: true
    
  # QUAST
  QUAST:
    "Total length": true
    "# contigs": true
    N50: true
    "Largest contig": true
    "# misassemblies": false
    GC: false
    
  # Mosdepth (configuración para profundidades específicas)
  Mosdepth:
    "1X": true
    "5X": true
    "10X": true
    "30X": false
    "50X": false
    
  # Prokka
  Prokka:
    CDS: false
    tRNA: false
    tmRNA: false
    rRNA: false
    Organism: false
    
  # Kraken (si añade columnas al general stats)
  Kraken:
    percent_classified: true
    percent_unclassified: true

# 2. Orden de columnas (valores menores = más a la izquierda)
table_columns_placement:
  # GRUPO 1: Calidad de lecturas (100-299)
  NanoStat:
    "Number of reads_fastq": 100
    "Total bases_fastq": 110
    "Mean read length_fastq": 120
    "Median read length_fastq": 130
    "Read length N50_fastq": 140
    "Mean read quality_fastq": 150
    
  # GRUPO 2: Calidad del ensamblaje (300-499)
  QUAST:
    "Total length": 300
    "# contigs": 310
    N50: 320
    "Largest contig": 330
    
  # GRUPO 3: Calidad del genoma (500-599)
  CheckM2:
    Completeness: 500
    Contamination: 510
    
  # GRUPO 4: Mapeo (600-799)
  "Samtools Stats":
    raw_total_sequences: 600
    reads_mapped: 610
    reads_mapped_percent: 620
    average_length: 630
    
  "Samtools Flagstat":
    mapped_passed: 700
    mapped_passed_pct: 710
    
  # GRUPO 5: Cobertura (800-899)
  Mosdepth:
    "1X": 800
    "5X": 810
    "10X": 820
    "30X": 830
    
  # GRUPO 6: Anotación (900-999)
  Prokka:
    CDS: 900
    tRNA: 910
    
  # GRUPO 7: Taxonomía (1000-1099)
  Kraken:
    percent_classified: 1000
    percent_unclassified: 1010

# 3. Renombrar columnas para mejor comprensión
table_columns_name:
  # NanoStat - nombres más descriptivos
  NanoStat:
    "Number of reads_fastq": "Nº Lecturas"
    "Total bases_fastq": "Bases Totales (bp)"
    "Mean read length_fastq": "Longitud Media"
    "Median read length_fastq": "Longitud Mediana"
    "Read length N50_fastq": "N50 Lecturas"
    "Mean read quality_fastq": "Calidad Media"
    
  # QUAST - Assembly metrics
  QUAST:
    "Total length": "Tamaño Ensamblaje (bp)"
    "# contigs": "Nº Contigs"
    N50: "N50 Ensamblaje"
    "Largest contig": "Contig Mayor (bp)"
    
  # CheckM2 - Genome quality
  CheckM2:
    Completeness: "Completitud (%)"
    Contamination: "Contaminación (%)"
    
  # Samtools - Mapping metrics
  "Samtools Stats":
    raw_total_sequences: "Secuencias Totales"
    reads_mapped: "Lecturas Mapeadas"
    reads_mapped_percent: "% Mapeado"
    average_length: "Longitud Promedio"
    
  "Samtools Flagstat":
    mapped_passed: "Mapeadas QC"
    mapped_passed_pct: "% Mapeadas QC"
    
  # Mosdepth - Coverage
  Mosdepth:
    "1X": "Cobertura ≥1X (%)"
    "5X": "Cobertura ≥5X (%)"
    "10X": "Cobertura ≥10X (%)"
    "30X": "Cobertura ≥30X (%)"
    
  # Prokka - Annotation
  Prokka:
    CDS: "Genes CDS"
    tRNA: "Genes tRNA"
    
  # Kraken - Taxonomy
  Kraken:
    percent_classified: "% Clasificado"
    percent_unclassified: "% Sin Clasificar"
    
  # Renombrar columnas generales si aparecen
  general_stats_table:
    cov: "Coverage Assembly"
    coverage: "Cobertura Media"

# 4. Configuración específica de Mosdepth para profundidades de cobertura
mosdepth_config:
  general_stats_coverage: [1, 5, 10, 30]

# 5. Configuración de Kraken
kraken:
  top_n: 5

# Añade esta sección a tu multiqc_config.yml

# Añade esta sección a tu multiqc_config.yml

custom_data:
  # ID único para nuestra tabla de BUSCO
  busco_summary:
    # Nombre de la sección que aparecerá en el informe
    section_name: "BUSCO Summary"
    description: "Métricas clave de completitud del análisis con BUSCO."
    plot_type: "table"
    # pconfig personaliza la tabla
    pconfig:
      id: "busco_summary_table"
      title: "Resumen de BUSCO"
      namespace: "BUSCO"
    # Definición de cada columna
    headers:
      'BUSCO_C(%)':
        title: 'Completo (%)'
        description: 'Porcentaje de BUSCOs completos (Copia Única + Duplicados).'
        format: '{:.1f}' # Un decimal
        suffix: '%'
      'BUSCO_S(%)':
        title: 'Único (%)'
        description: 'Porcentaje de BUSCOs completos y de copia única.'
        format: '{:.1f}'
        suffix: '%'
      'BUSCO_D(%)':
        title: 'Duplicado (%)'
        description: 'Porcentaje de BUSCOs completos y duplicados.'
        format: '{:.1f}'
        suffix: '%'
        hidden: True # Oculta esta columna por defecto
      'BUSCO_F(%)':
        title: 'Fragmentado (%)'
        description: 'Porcentaje de BUSCOs fragmentados.'
        format: '{:.1f}'
        suffix: '%'
        max: 5 # Pone en rojo valores por encima de 5
      'BUSCO_M(%)':
        title: 'Ausente (%)'
        description: 'Porcentaje de BUSCOs ausentes.'
        format: '{:.1f}'
        suffix: '%'
        max: 5 # Pone en rojo valores por encima de 5


report_comment: "<b>RUN:</b> 250822_EPIM231"